### ISSUE TITLE
Trader 参数如何传参数

### ISSUE THREAD

**Issue by hejizhang** [nooperpudd/ctpwrapper#17]
在使用samples/trader_main.py中,想调用user_trader.ReqQrySecAgentTradingAccount
知道这个函数在ctpwapper/trader.py中需要二个参数(self, pQryTradingAccount, nRequestID)
问,这二个参数如何构建

**Comment by nooperpudd** [comment]
`ApiStructure.QryTradingAccountField`

        ('BrokerID', ctypes.c_char * 11),  # 经纪公司代码
        ('InvestorID', ctypes.c_char * 13),  # 投资者代码
        ('CurrencyID', ctypes.c_char * 4),  # 币种代码
        ('BizType', ctypes.c_char),  # 业务类型
        ('AccountID', ctypes.c_char * 13),  # 投资者帐号

ApiStructure.QryTradingAccountField(BrokerID="",InvestorID="",...)

**Comment by hejizhang** [comment]
谢谢,BrokerID和InvestorID可以找的到 CurrencyID,BizType,AccountID 这三个是什么,我去那里能找到

**Comment by hejizhang** [comment]
资料中,
doc/ctp/综合交易平台TraderAPI接口说明.pdf 
讲这个要求参数只有BrokerID,InvestorID二个参数,跟你的不一样, 是接口版本不样么?

内容如下:

6.5.26. ReqQryTradingAccount 方法

pQryTradingAccount：指向查询资金账户结构的地址。
查询资金账户结构：
struct CThostFtdcQryTradingAccountField 
{
///经纪公司代码
TThostFtdcBrokerIDType BrokerID;
///投资者代码
TThostFtdcInvestorIDType InvestorID;
};

**Comment by nooperpudd** [comment]
版本不一样，建议看下CTP的文档。

**Comment by hejizhang** [comment]
还有个问题,ctpwrapper/Trader.py文件中,
def Onxxxx(self):
        pass

都是这种状态,这些功能还没有完成还是可以有参考上面def Reqxxxx这样的方式自己补全?
