### ISSUE TITLE
small issue, "Md" should be "Td"

### ISSUE THREAD

**Issue by renc** [nooperpudd/ctpwrapper#23]
Hello, 

samples\td_main.py, OnRspUserLogin()

print("Md OnRspUserLogin failed error_id=%s msg:%s",
print("Md user login successfully")

the "Md" should be "Td", that will make them more clear. thank you.

**Comment by nooperpudd** [comment]
where is `td_main.py`?

**Comment by renc** [comment]
my fault , the file is https://github.com/nooperpudd/ctpwrapper/blob/master/samples/trader_main.py
