### ISSUE TITLE
关于CTP API 升级成穿透式监管评测版本 

### ISSUE THREAD

**Issue by ffllc** [nooperpudd/ctpwrapper#30]
您好, 接到期货公司通知, 19年6月份会停用目前的api  要求启用穿透式监管评测版本 的api.请问有升级计划吗?
http://www.sfit.com.cn/5_2_DocumentDown.htm
这里有提供启用穿透式监管评测版本

**Comment by nooperpudd** [comment]
ok

**Comment by wuxiaoq** [comment]
请问最近在着手升级6.3.15了吗？

**Comment by stockwiner** [comment]
好着急呀
