### ISSUE TITLE
例子程序运行失败

### ISSUE THREAD

**Issue by omytea** [nooperpudd/ctpwrapper#33]
运行sample下的trader_main.py

```
ubuntu@VM-0-3-ubuntu:~/ctp_quote_test$ python3 ctp_test_2.py
trader on front connection
Md user login successfully
trader started
20190111
Segmentation fault (core dumped)
```

**Comment by nooperpudd** [comment]
show code detail

**Comment by omytea** [comment]
> show code detail

same code as samples/trader_main.py

what I did is install the package from pip and then create a file with the content from sample code. You may check from repo or I can quote it here.

`
user_trader = Trader(broker_id=broker_id, investor_id=investor_id, password=password)

        user_trader.Create()
        user_trader.RegisterFront(server)
        user_trader.SubscribePrivateTopic(2) # 只传送登录后的流内容
        user_trader.SubscribePrivateTopic(2) # 只传送登录后的流内容

        user_trader.Init()

        print("trader started")
        print(user_trader.GetTradingDay())

        user_trader.Join()
`

**Comment by hadrianl** [comment]
Probably,it is a bug in the commit  9b4cc58.You might try to del "self.ReqQryInvestor(inv, self.inc_request_id())" in callbackfunc "OnRspUserLogin".If it works, that would be the bug I refered last week.Downgrade ctpwraper to 6.3.11.6,  Problem solved

**Comment by omytea** [comment]
@hadrianl 
I tried your method and it execute as you said.

**Comment by nooperpudd** [comment]
ok, I will test.
