### ISSUE TITLE
anyone upgrade to 6.3.15 successfully?

### ISSUE THREAD

**Issue by stockwiner** [nooperpudd/ctpwrapper#39]
I am not.
show much errors.

**Comment by nooperpudd** [comment]
error messages, please.

**Comment by xliaoong** [comment]
俩中国人非要用英语，这样好吗？

**Comment by stockwiner** [comment]
[t.txt](https://github.com/nooperpudd/ctpwrapper/files/3239550/t.txt)

**Comment by stockwiner** [comment]
有个简单的方法可以升级，就是把更新的文件拷贝到site-packages\ctpwrapper
问题是ctp 6.3.13在 TraderApi中新增了 ReqAuthenticate这个方法，需要调用这个。

**Comment by zjuhjm** [comment]
安装6.3.15 运行sample文件夹 md_main.py 
md.GetTradingDay()的返回值是1989年某日，并且没有返回行情数据
退回到6.3.11.6 没有问题
不知道是什么原因

**Comment by nooperpudd** [comment]
接口调用不一样，需要结合Datacollect header来。建议你们看下文档。谁可以的话可以发一个pull requests.

**Comment by stockwiner** [comment]
[CTP-API-Interfacedescription-ct.zip](https://github.com/nooperpudd/ctpwrapper/files/3241185/CTP-API-Interfacedescription-ct.zip)
接口调用的说明

**Comment by ruifeng96150** [comment]
换6.3.15的接口可以连接simnow的行情吗？之前听别人说只能连生产环境的地址
