### ISSUE TITLE
No callback?

### ISSUE THREAD

**Issue by hc128168** [nooperpudd/ctpwrapper#55]
I tried to modify your sample code -- trader_main.py as I got the following error:
```
  File "trade_monitor.py", line 229, in <module>
    main()
  File "trade_monitor.py", line 219, in main
    trader_account = ApiStructure.QryTradingAccountField(BrokerID=broker_id, InvestorID=investor_id)
  File "/home/hc/.local/lib/python3.8/site-packages/ctpwrapper/ApiStructure.py", line 2877, in __init__
    self.BizType = self._to_bytes(BizType)
TypeError: one character bytes, bytearray or integer expected
```
I fixed it by adding `, BizType='0'`.

Then, I noticed that `OnRspQryTradingAccount()` didn't get called.

Then, I removed `ReqQryInvestor()` and `ReqQryTradingAccount()` in your sample code, `OnRspQryTradingAccount()` did get called.

Any idea what's going on?

Thanks!

**Comment by nooperpudd** [comment]
https://github.com/nooperpudd/ctpwrapper/commit/cc8018dbe2ece4cee02be6a8beaa3708044f7671

**Comment by hc128168** [comment]
> [cc8018d](https://github.com/nooperpudd/ctpwrapper/commit/cc8018dbe2ece4cee02be6a8beaa3708044f7671)

It doesn't solve the issue of no callback for the 2nd ReqXXX() call tho....
